name: linttest
on : push

jobs:
    lints:
        run-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: action/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v4
    
        - run: test_linting.py
