name: CI-DEMO # 
on : push  # when to excute the workflow when push happen

jobs:
    lint:
        runs-on: ${{matrix.os}}    # setting up the env on which machine we want test the workflow( check os)

        strategy:
          matrix:
              os: [ubuntu-latest, windows-latest, macos-latest]
              python-version: ['3.9','3.10', '3.11','3.12']

        steps:                     # providing the task 
            - name: Checkout code   # checkout the code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with: 
                  python-version: ${{matrix.python-version}}

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8
              

            - name: Run flake8
              run: |
                flake8 test_linting.py  # excute python file with flake8




# name: linttest
# on: push

# jobs:
#   lint:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'  # or whatever version you prefer

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install flake8

#       - name: Run flake8
#         run: flake8 test_linting.py
        
