# name: linttest
# on : push

# jobs:
#     lint:
#         runs-on: ubuntu-latest

#         steps:
#             - name: Checkout code
#               uses: actions/checkout@v3

#             - name: Setup Python
#               uses: actions/setup-python@v4

#             - name: Install Dependencies
#               run: |
#                   python -m pip install --upgrade pip
#                   pip install flask8
              

#             - name: Run flask8
#               run: |
#                 flake8 test_linting.py




name: linttest
on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or whatever version you prefer

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 test_linting.py
        
